export type Page<T> = { items: T[]; next_cursor: string | null };
export type Category = {
  id: string;
  name: string;
  category_type: string;
  status: string;
  row_version: number;
  is_fallback: boolean;
  description?: string;
};
export type Snapshot = {
  id: string;
  balance: string;
  currency: string;
  as_of: string;
  row_version: number;
  status: string;
  time_basis: string;
};
export type Account = {
  id: string;
  household_id: string;
  name: string;
  account_type: string;
  currency: string;
  balance_scope: string;
  risk_level: string | null;
  status: string;
  row_version: number;
  statement_import_enabled: boolean;
  latest_snapshot: Snapshot | null;
  opened_on: string;
  owner_user_id: string | null;
};
export type Transaction = {
  id: string;
  schedule_occurrence_id?: string | null;
  occurred_on: string;
  original_amount: string;
  original_currency: string;
  transaction_type: string;
  category_id: string;
  account_id: string | null;
  merchant: string | null;
  remarks: string | null;
  row_version: number;
  category_uncertain: boolean;
  account_review_acknowledged: boolean;
  status: string;
};
export type Warning = {
  code: string;
  row_id?: string | null;
  message?: string;
};
export type StatementLine = {
  row_id: string;
  row_no: number;
  action: "create" | "skip" | "link_existing" | "use_schedule_period";
  occurred_on: string | null;
  original_amount: string | null;
  original_currency: string | null;
  transaction_type: "expense" | "refund" | null;
  category_id: string | null;
  category_uncertain: boolean;
  merchant: string | null;
  remarks: string | null;
  reason?: string | null;
  kind?: string;
  requires_review: boolean;
  duplicate_ids: string[];
  transaction_id?: string | null;
  expected_transaction_version?: number | null;
  schedule_id?: string | null;
  expected_schedule_version?: number | null;
  period_no?: number | null;
  explicit_create?: boolean;
  confirm_facts?: boolean;
};
export type BalanceRow = {
  row_id: string;
  selected: boolean;
  account_id: string | null;
  balance: string | null;
  currency: string | null;
  as_of: string | null;
  time_basis: string;
  expected_account_version: number | null;
  expected_latest_snapshot_id: string | null;
  reuse_snapshot_id?: string | null;
  exclusion_reason?: string | null;
  requires_review?: boolean;
  label?: string;
};
export type StatementDraft = {
  account_id: string;
  lines: StatementLine[];
  balance: BalanceRow | null;
  period_start: string | null;
  period_end: string | null;
  partial: boolean;
  identity_ok: boolean;
  acknowledge_partial: boolean;
  confirm_account_identity: boolean;
  warnings: Warning[];
};
export type Receipt<D = StatementDraft> = {
  request_id: string;
  status: string;
  row_version: number;
  draft: D;
  warnings: Warning[];
  counts?: { create: number; link: number; skip: number };
  snapshots?: Snapshot[];
};
export type WealthAccount = {
  account_id: string;
  name: string;
  account_type: string;
  currency: string;
  balance: string | null;
  converted_amount: string | null;
  as_of: string | null;
  age_days: number | null;
  needs_update: boolean;
  very_stale: boolean;
  balance_scope: string;
};
export type Wealth = {
  reporting_currency: string;
  setup_required: boolean;
  total_assets: string | null;
  total_liabilities: string | null;
  net_worth: string | null;
  known_assets: string;
  known_liabilities: string;
  known_net_worth: string;
  accounts: WealthAccount[];
  risk_buckets: {
    risk_level: string;
    amount: string;
    percentage: string | null;
  }[];
  coverage: {
    complete: boolean;
    missing_account_ids: string[];
    stale_account_ids: string[];
    missing_fx_currencies: string[];
    stale_fx_currencies: string[];
    oldest_observation_at: string | null;
    newest_observation_at: string | null;
  };
};
export type Totals = {
  gross_expenses: string | null;
  refunds: string | null;
  net_spending: string | null;
  known_gross_expenses: string;
  known_refunds: string;
  known_net_spending: string;
  missing_conversion_count: number;
};
export type Spending = Totals & {
  reporting_currency: string;
  from: string;
  to: string;
  schedules_current_through: string | null;
  category: (Totals & { key: string })[];
  month: (Totals & { key: string })[];
};
export type ReviewCounts = {
  transactions: number;
  drafts: number;
  schedule_occurrences: number;
  unusual_investment_estimates: number;
};
export type Review<T = Transaction> = Page<T> & {
  counts: ReviewCounts;
  settings_row_version: number;
  investment_review_change_ratio: string;
};
export type Investment = {
  id: string;
  account_name: string;
  currency: string;
  opening_snapshot_id: string;
  closing_snapshot_id: string;
  period_start: string;
  period_end: string;
  opening_value: string;
  closing_value: string;
  gain: string;
  gain_status: string;
  input_id: string | null;
  input_version: number | null;
  effective_contributions: string;
  effective_withdrawals: string;
  needs_review: boolean;
};
export type Schedule = {
  id: string;
  name: string;
  kind: string;
  currency: string;
  amount_per_period: string;
  status: string;
  row_version: number;
  period_count: number | null;
  day_of_month: number;
  start_month: string;
  category_id: string;
  account_id: string | null;
  merchant: string | null;
};
